In [1]:
import numpy as np

# Create Array

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr = np.array([1,2,3,4,5.0])
arr

array([1., 2., 3., 4., 5.])

In [5]:
arr.dtype

dtype('float64')

In [6]:
arr = np.array([1,2,3,4,5],float)
print(arr.dtype)    # float64

float64


In [7]:
arr = np.array([1,2,3,4,5],int)
print(arr.dtype)    # int32

int32


# linspace(start,end,parts)

In [8]:
arrLin=np.linspace(0,16)
arrLin
# why output in float because you breaks into parts i,e 16 parts

array([ 0.        ,  0.32653061,  0.65306122,  0.97959184,  1.30612245,
        1.63265306,  1.95918367,  2.28571429,  2.6122449 ,  2.93877551,
        3.26530612,  3.59183673,  3.91836735,  4.24489796,  4.57142857,
        4.89795918,  5.2244898 ,  5.55102041,  5.87755102,  6.20408163,
        6.53061224,  6.85714286,  7.18367347,  7.51020408,  7.83673469,
        8.16326531,  8.48979592,  8.81632653,  9.14285714,  9.46938776,
        9.79591837, 10.12244898, 10.44897959, 10.7755102 , 11.10204082,
       11.42857143, 11.75510204, 12.08163265, 12.40816327, 12.73469388,
       13.06122449, 13.3877551 , 13.71428571, 14.04081633, 14.36734694,
       14.69387755, 15.02040816, 15.34693878, 15.67346939, 16.        ])

In [9]:
arrLin1=np.linspace(0,16,20)
# break into 20 parts
arrLin1

array([ 0.        ,  0.84210526,  1.68421053,  2.52631579,  3.36842105,
        4.21052632,  5.05263158,  5.89473684,  6.73684211,  7.57894737,
        8.42105263,  9.26315789, 10.10526316, 10.94736842, 11.78947368,
       12.63157895, 13.47368421, 14.31578947, 15.15789474, 16.        ])

In [10]:
arrLin2=np.linspace(0,15)  #linspace(start,end,parts)
# parts is not specfic then it breaks according to(0-15 = 16 parts)
print(arrLin2)  # output = [0. 0.306----------------- 15.]

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


# arange(start,end,step) # end not include

In [11]:
arr=np.arange(1,15,2)
print(arr) # output = [1 5 7 9 11 13]

[ 1  3  5  7  9 11 13]


# logspace()

In [12]:
arr = np.logspace(1,40,5)
print(arr)


[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [13]:
print('%.2f'%arr[0]) # for 2 digit decimal

10.00


In [14]:
print('%.2f'%arr[4])

10000000000000000303786028427003666890752.00


# Zeroes

In [15]:
arr = np.zeros(5)
print(arr) # [0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0.]


# Ones

In [16]:
arr=np.ones(5)
print(arr) # [1. 1. 1. 1. 1.]

[1. 1. 1. 1. 1.]


In [17]:
arr=np.ones(5,int)
print(arr) # [1 1 1 1 1]

[1 1 1 1 1]


# adding arr with 5

In [18]:
arr = np.array([1,2,3,4,5])
arr=arr+5
print(arr) # [6 7 8 9 10]

[ 6  7  8  9 10]


# Add two array. It is also called vectorized operation

In [19]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
arr3=arr1+arr2
print(arr3) #[2 4 6 8 10]

[ 2  4  6  8 10]


# Math operation

## trignometry operation

In [20]:
arr = np.array([1,2,3,4,5])
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [21]:
print(np.cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


## log

In [22]:
arr = np.array([1,2,3,4,5])
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

## Square Root

In [23]:
arr = np.array([1,2,3,4,5])
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

## sum of array

In [24]:
arr1 = np.array([1,2,3,4,5])
np.sum(arr)

15

## min and max

In [25]:
arr = np.array([1,2,3,4,5])
print(np.min(arr))

1


In [26]:
print(np.max(arr))

5


## Unique Element in Array

In [27]:
arr = np.array([1,2,3,4,5,5,1,6,7,6])
print(np.unique(arr))

[1 2 3 4 5 6 7]


## Sort

In [28]:
arr = np.array([1,20,3,4,5,10,100,45,50,6])
print(np.sort(arr))

[  1   3   4   5   6  10  20  45  50 100]


In [29]:
# np.sort() function does not allow to sort by descending order
arr = np.array([1,20,3,4,5,10,100,45,50,6])
sortedArr=np.sort(arr)
print(sortedArr[::-1])

[100  50  45  20  10   6   5   4   3   1]


# concatenate

In [30]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([30,20,35,40,50])
print(np.concatenate((arr1,arr2)))

[ 1  2  3  4  5 30 20 35 40 50]


In [31]:
arr1=np.array([ [1,2,3], [4,5,6] ])
arr2=np.array([ [30,20,35] ])
print(np.concatenate((arr1,arr2),axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [30 20 35]]


# Copy an array

In [33]:
arr1=np.array([1,2,3,4,5])
arr2=arr1

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [36]:
arr2

array([1, 2, 3, 4, 5])

## But both array have same address

In [40]:
id(arr1)

746602197600

In [41]:
id(arr2)

746602197600

## I want to create with different address

In [43]:
arr1=np.array([1,2,3,4,5])
arr2=arr1.view()

In [44]:
arr1

array([1, 2, 3, 4, 5])

In [45]:
arr2

array([1, 2, 3, 4, 5])

id(arr1)

In [47]:
id(arr2)

746602200320

## Two types of Copy
## 1. Shallow Copy = both array have different address but both array are still depend on each other
## 2. Deep Copy = Deep Copy = both array are independent to each other

### 1. Shallow Copy Example

In [51]:
arr1=np.array([1,2,3,4,5])
arr2=arr1.view()

In [52]:
arr1

array([1, 2, 3, 4, 5])

In [53]:
arr2

array([1, 2, 3, 4, 5])

In [54]:
# update value at index 1 in arr1
arr1[1]=7

In [55]:
arr1

array([1, 7, 3, 4, 5])

In [57]:
# But arr2 is also update because arr2 is depend on arr1
arr2

array([1, 7, 3, 4, 5])

### Deep Copy Example

In [58]:
arr1=np.array([1,2,3,4,5])
arr2=arr1.copy()

In [59]:
arr1

array([1, 2, 3, 4, 5])

In [60]:
arr2

array([1, 2, 3, 4, 5])

In [61]:
# update value at index 1 in arr1
arr1[1]=7

In [62]:
arr1

array([1, 7, 3, 4, 5])

In [63]:
# arr2 array is not updated becouse both arrays are independent to each other
arr2

array([1, 2, 3, 4, 5])

# Write a code to add 2 arrays using forloop

In [69]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,80,100])
arr3=np.array([])

In [73]:
for i in range(0,len(arr1)):
    val=arr1[i]+arr2[i]
    print(val,end=' ')

60 80 110 140 

# write a code to find the maximum value from an array without using in-build function

In [81]:
arr1=np.array([10,20,8050,900,56,6,1000])

In [82]:
max=arr1[i]
for i in range(len(arr1)):
    if max<arr1[i]:
        max=arr1[i]
print(max)

8050


# Multi dimension array

In [84]:
arr=np.array([
        [1,2,3],
        [4,5,6]
])

In [85]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [86]:
print(arr.dtype)

int32


In [87]:
print(arr.ndim)

2


In [89]:
print(arr.shape)   #(2,3) i.e (rows,cols)

(2, 3)


In [90]:
print(arr.size)    # 6 i.e total no. of element 

6


# Convert 2D array into 1D array

In [92]:
arr=np.array([
        [1,2,3],
        [4,5,6]
    ])

In [93]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [95]:
# After Convert
arr2=arr.flatten()
arr2

array([1, 2, 3, 4, 5, 6])

In [96]:
print(arr2.ndim)

1


# Convert 2D to 3D array

In [97]:
arr1=np.array([
        [1,2,3,4,5,6],
        [7,5,2,8,9,1]
    ])

In [98]:
arr2= arr1.reshape(3,4) # 2D but row,col = (3,4)

In [99]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 5],
       [2, 8, 9, 1]])

In [100]:
arr3=arr1.reshape(2,2,3) # 3D = 2array, 2row, 3 cols

In [101]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 5, 2],
        [8, 9, 1]]])

# Matrices

In [102]:
arr1=np.array([
        [1,2,34,2],
        [4,5,6,6]
    ])

In [106]:
m1 = np.matrix(arr1)

In [107]:
m1

matrix([[ 1,  2, 34,  2],
        [ 4,  5,  6,  6]])

In [113]:
m2 = np.matrix('1 2 3 ; 4 5 6 ; 7 8 9')

In [114]:
m2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [118]:
# Find Diagonal
print(np.diagonal(m2)) # 1 5 9

[1 5 9]


In [119]:
# Min and Max
print(m2.min())

1


In [120]:
print(m2.max())

9


# Multiple matrices

In [122]:
m1 = np.matrix('1 2 3; 4 5 6 ; 7 8 9')
m2 = np.matrix('1 2 3; 4 5 6 ; 7 8 9')

In [129]:
# Addition
m3 = m1+m2;
m4=m1*m2;

In [130]:
# Multiple
m4=m1*m2;
m4

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])